[project]
name = "testcontainers-yt-local"
authors = [
    {name = "Dmitriy Fedorov"},
]
requires-python = ">=3.8"
license = {text = "Apache 2.0"}
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["."]
