name: tests

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: "Install lib"
        run: pip install ".[tests]"

      - name: "Run tests"
        run: pytest ./tests -s
